### ISSUE TITLE
SolidCable::TrimJob does not remove messages

### ISSUE THREAD

**Issue by chrisdebruin** [rails/solid_cable#61]
I'am using this config
```
default: &default
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 1.second
  message_retention: 1.day
  autotrim: false
```

And running `SolidCable::TrimJob` with `solid_queue` but noticed that no messages are being deleted. 
I tnink it's because of this line https://github.com/rails/solid_cable/blob/main/app/jobs/solid_cable/trim_job.rb#L20

Should `trim?` just return true when you set `autotrim: false` ?
